artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/omarlahbibi/Branching-data/raw/refs/heads/main/rossmann-store-sales.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["sales.csv", "store.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  sales_file: artifacts/data_ingestion/rossmann-store-sales/sales.csv
  store_file: artifacts/data_ingestion/rossmann-store-sales/store.csv
  cleaned_data_file: artifacts/data_transformation/sales_store_cleaned.csv
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv
  test_size: 0.2

model_trainer:
  root_dir: artifacts/model_trainer
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv
  model_file: artifacts/model_trainer/catboost_model.cbm